[build]
  command = "npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*.js"
    [headers.values]
    Access-Control-Allow-Origin = "*"
  for = "/*.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
